AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Document OCR via Textract and Rekognition

Globals:
  Function:
    Timeout: 20
    MemorySize: 128
    Runtime: python3.10
    Architectures:
        - arm64
    ReservedConcurrentExecutions: 1


Resources:
  DocumentOCRFunction:
    Type: AWS::Serverless::Function 
    Description: 'Lambda function that is invoked via S3 upload Event, that sends documents to Rekognition and saved Rekognition response into DynamoDB'
    Properties:
      CodeUri: dms-lambda/
      Handler: doc.lambda_handler
      Environment:
        Variables:
          DocumentTable: !Ref DocumentTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentTable 
        - AWSLambdaExecute 
        - RekognitionDetectOnlyPolicy: {}
        - Statement:
            - Effect: Allow
              Action: s3:*
              Resource: "arn:aws:s3:::dms-sam/*"
      Events:
        DocumentUpload:
          Type: S3
          Properties:
            Bucket: 
              Ref: DocumentBucket
            Events: s3:ObjectCreated:*

  DynamoDBFunction:
    Type: AWS::Serverless::Function
    Description: 'Lambda function that is invoked via APIGW, that requests document data from DynamoDB table'
    Properties:
      FunctionName: WeatherFunction
      Handler: apigw2dynamo.lambda_handler
      Runtime: python3.8
      CodeUri: dms-lambda/
      Environment:
        Variables:
          DocumentTable: !Ref DocumentTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref DocumentTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: GET
            Auth:
              ApiKeyRequired: true

            
  DocumentBucket: 
    Type: AWS::S3::Bucket
    Properties:
      BucketName: idp-dms

  DocumentTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions:
        - AttributeName: dms_id
          AttributeType: S
        - AttributeName: document
          AttributeType: S
      KeySchema:
        - AttributeName: dms_id
          KeyType: HASH
        - AttributeName: document
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      TableName: DocumentOCR


Outputs:
  EndpointUrl:
    Description: 'HTTP REST endpoint URL'
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
